Q1.
Create a 1D NumPy array of the first 10 even numbers using np.arange(), and print its shape, size, and dtype


In [5]:
import numpy as np

arr = np.arange(2, 21, 2)  
print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dtype:", arr.dtype)

Array: [ 2  4  6  8 10 12 14 16 18 20]
Shape: (10,)
Size: 10
Dtype: int64


Q2.
Create a 4x4 identity matrix using np.eye(), then create a separate 4x4 array filled entirely with the value 9 using np.full().


In [6]:
identity = np.eye(4)
print(identity)

filled = np.full((4, 4), 9)
print(filled)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


Q3.
Create a 2D array representing a 3x3 grid of your choice. Print the element at row 2, column 1, and then print the entire second row.


In [7]:
grid = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Element at row 2, col 1:", grid[2, 1])
print("Entire second row:", grid[1])

Element at row 2, col 1: 8
Entire second row: [4 5 6]


Q4.
Create a 1D array of 20 numbers using np.arange(), then use slicing to extract every 3rd element starting from index 2.


In [8]:
arr = np.arange(20)
print("Original:", arr)

sliced = arr[2::3]
print("Every 3rd from index 2:", sliced)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Every 3rd from index 2: [ 2  5  8 11 14 17]


Q5.
Create a 5x5 2D array using np.arange() and reshape (Hint: research np.arange(25).reshape(5,5) briefly), then slice out the middle 3x3 sub-grid.


In [9]:
matrix = np.arange(25).reshape(5, 5)
print("Full matrix:\n", matrix)

middle = matrix[1:4, 1:4]
print("\nMiddle 3x3:\n", middle)

Full matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Middle 3x3:
 [[ 6  7  8]
 [11 12 13]
 [16 17 18]]


Q6.
Demonstrate the 'slices are views, not copies' behavior: create an array, slice it, modify the slice, and print both the original and the slice to show the original changed too. Then fix it using .copy().


In [10]:
arr = np.array([10, 20, 30, 40, 50])
sl = arr[1:4]        # this is a VIEW, not a copy

sl[0] = 999            # modify the slice
print("Original after modifying slice:", arr)
print("Slice:", sl)

# Fix using .copy()
arr2 = np.array([10, 20, 30, 40, 50])
sl_copy = arr2[1:4].copy()
sl_copy[0] = 999
print("\nOriginal after modifying the copy:", arr2)
print("Copy:", sl_copy)

Original after modifying slice: [ 10 999  30  40  50]
Slice: [999  30  40]

Original after modifying the copy: [10 20 30 40 50]
Copy: [999  30  40]


Q7.
Create an array of 10 evenly spaced values between 0 and 100 using np.linspace(), and print the result.


In [11]:
arr = np.linspace(0, 100, 10)
print(arr)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


Q8.
Create an array with mixed integers and floats (e.g., [1, 2, 3.5]), print its dtype, and explain in a comment why NumPy chose that type.


In [12]:
arr = np.array([1, 2, 3.5])
print(arr)
print("Dtype:", arr.dtype)

# NumPy arrays must hold a SINGLE dtype for all elements (unlike Python lists).
# Since 3.5 can't be represented as an int without losing data, NumPy
# "upcasts" the entire array to float64 so no information is lost —
# the ints 1 and 2 become 1.0 and 2.0.

[1.  2.  3.5]
Dtype: float64


Q9.
Create a float array [3.2, 7.8, 1.1, 9.9] and convert it to an integer array using .astype(int). Print both arrays and explain what happened to the decimal values.


In [13]:
floats = np.array([3.2, 7.8, 1.1, 9.9])
ints = floats.astype(int)

print("Float array:", floats)
print("Integer array:", ints)

# .astype(int) TRUNCATES (chops off) the decimal part — it does NOT round.
# 3.2 -> 3, 7.8 -> 7 (not 8!), 1.1 -> 1, 9.9 -> 9 (not 10!)

Float array: [3.2 7.8 1.1 9.9]
Integer array: [3 7 1 9]


Q10.
Create a 3x4 array of zeros using np.zeros(), then use indexing to set the entire second row to the value 5 and the entire third column to the value 8. Print the final array.


In [14]:
arr = np.zeros((3, 4))
print("Original:\n", arr)

arr[1, :] = 5   # entire second row (index 1)
arr[:, 2] = 8   # entire third column (index 2)

print("\nFinal array:\n", arr)

Original:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Final array:
 [[0. 0. 8. 0.]
 [5. 5. 8. 5.]
 [0. 0. 8. 0.]]
